### ISSUE TITLE
[Flaky Test] Ironic database is locked

### ISSUE THREAD

**Issue by mboukhalfa** [metal3-io/cluster-api-provider-metal3#1082] opened 2023-07-10 16:47 UTC
### Which jobs are flaking?
 Multiple jobs including:

-  [Clusterctl upgrade](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-0-5_main_e2e_clusterctl_upgrade_test_ubuntu/)
- [BML integration](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-1-4_main_e2e_clusterctl_upgrade_test_ubuntu/45/)
- [Feature test - Pivoting based tests](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_e2e_feature_test_centos/161/)

### Which tests are flaking?
Multiple tests when ironic is involved for inspection or cleaning 

- [04_verify.sh](https://github.com/metal3-io/metal3-dev-env/blob/main/04_verify.sh) 
- [Clusterctl_upgrade](https://github.com/kubernetes-sigs/cluster-api/blob/7b92ce4577e36adf013dc1dfd2b239fde4c36bc4/test/e2e/clusterctl_upgrade.go#L557C17-L557C17) when deleting the cluster

### Since when has it been flaking?
First occurrence noticed Jun 30, 2023, 4:30:00 AM EEST https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_release-1-2_integration_test_centos/303/console

### Reason for failure (if possible)
Ironic database is locked

Event logs in from the tarball path `_artifacts/clusters/bootstrap/resources/clusterctl-upgrade-kprxc0/` in [this Jenkins test link](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-0-5_main_e2e_clusterctl_upgrade_test_ubuntu/34/)
```
[New Event] clusterctl-upgrade-kprxc0/InspectionError-hxbtr
        resource: metal3.io/v1alpha1/BareMetalHost/node-1
        reason: InspectionError
        message: Unexpected exception HttpException during processing: HttpException: 500: Server Error for url: https://172.22.0.2:6385/v1/nodes/fbbcf188-af91-431d-af65-aa2cddf31ef0, (sqlite3.OperationalError) database is locked
```
Ironic logs from the tarball path `docker/after_pivoting/ironic` from [this job link](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-1-4_main_e2e_clusterctl_upgrade_test_ubuntu/45/)
```
2023-07-09 02:44:44.529 1 DEBUG sushy.connector [None req-cd7396e9-c634-4301-beed-d1d045cf4e91 - - - - - -] HTTP request: GET http://192.168.111.1:8000/redfish/v1/Systems/d8f37d44-fb73-4e98-a539-8d4540dbb71c; headers: {'OData-Version': '4.0'}; body: None; blocking: False; timeout: 60; session arguments: {}; _op /usr/lib/python3.9/site-packages/sushy/connector.py:144[00m
2023-07-09 02:44:44.531 1 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): ipmitool -I lanplus -H 192.168.111.1 -L ADMINISTRATOR -p 6230 -U admin -R 1 -N 5 -f /tmp/tmp3tu4qg4j power status execute /usr/lib/python3.9/site-packages/oslo_concurrency/processutils.py:384[00m
2023-07-09 02:44:44.540 1 ERROR ironic.conductor.base_manager [-] Error while heartbeating. Error: (sqlite3.OperationalError) database is locked
```
Ironic logs from tarball path [`k8s_management_cluster/baremetal-operator-system/baremetal-operator-ironic-7d45f766f7-xb96f/ironic/`] in [this job link](https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_bml_integration_tests_centos/473/)
```
2023-07-10 04:09:11.546 1 ERROR ironic.conductor.utils [None req-cc9f0ab0-041b-48fc-b27d-d4b35f481d40 - - - - - -] Failed to prepare node 6e2d9ac1-7c7e-4b3e-b1f0-e1563de5b422 for cleaning: (sqlite3.OperationalError) database is locked
```

### Anything else we need to know?
The issue has been reported to the ironic community, and there is a potential fix available :
https://review.opendev.org/c/openstack/ironic/+/888188
https://review.opendev.org/c/openstack/ironic/+/887853

/kind flake

**Comment by mboukhalfa** [comment] 2023-07-10 16:49
cc @dtantsur

**Comment by mboukhalfa** [comment] 2023-07-14 09:08
The fix https://review.opendev.org/c/openstack/ironic/+/888188 has been merged

**Comment by mboukhalfa** [comment] 2023-07-17 15:30
The patch https://review.opendev.org/c/openstack/ironic/+/888188 did not fully fixed the issue here are more patch open on ironic :
https://review.opendev.org/c/openstack/ironic/+/888500
https://review.opendev.org/c/openstack/ironic/+/888506

**Comment by mboukhalfa** [comment] 2023-07-27 08:21
fix are merged but few tests are still failing with this issue e.g https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_integration_test_centos/428/consoleFull
it is not clear if this tests are using the latest ironic image or an old one this has to be investigated

**Comment by Sunnatillo** [comment] 2023-08-16 05:55
happened here again: 
https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_release-1-4_e2e_integration_test_ubuntu/128/console

**Comment by Sunnatillo** [comment] 2023-08-17 05:52
https://jenkins.nordix.org/job/metal3_metal3_dev_env_main_e2e_integration_test_ubuntu/130

**Comment by Sunnatillo** [comment] 2023-08-17 14:00
https://jenkins.nordix.org/job/metal3_capm3_main_integration_test_centos/18/

**Comment by Sunnatillo** [comment] 2023-08-17 16:17
https://jenkins.nordix.org/job/metal3_project_infra_main_integration_test_ubuntu/215/

**Comment by Sunnatillo** [comment] 2023-08-18 07:07
https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_main_e2e_1-26-1-27_upgrade_test_ubuntu/79/consoleFull

**Comment by dtantsur** [comment] 2023-08-21 17:24
We've merged yet another patch that may help. Please let us know how it goes.

https://review.opendev.org/c/openstack/ironic/+/891333

**Comment by lentzi90** [comment] 2023-08-22 07:15
I think this is an occurrence: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_release-1-2_e2e_feature_test_ubuntu/188/
```
2023-08-21 11:39:55.143 1 DEBUG ironic.db.sqlalchemy.api [None req-bb2f1096-76bb-4fdd-b36e-1bb05a02026e - - - - - -] Retrying None in 0.11939437310540749 seconds as it raised OperationalError: (sqlite3.OperationalError) database is locked
```

Not sure if the patch was included here, I guess not?

**Comment by lentzi90** [comment] 2023-08-23 07:48
https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_release-1-2_integration_test_ubuntu/357/

**Comment by juliakreger** [comment] 2023-08-23 20:26
Greetings, the latest logs helped provide some clarity since the order of operations was just different enough that it highlighted the area of the behavior a bit better for us to figure out what is likely going on. This has resulted in https://review.opendev.org/c/openstack/ironic/+/892621 which is presently in review.

Somewhat related is https://review.opendev.org/c/openstack/ironic/+/892414 and
https://review.opendev.org/c/openstack/ironic-python-agent/+/891357. The tl;dr is that we could get a node locked, and that could cascade with introspection actually making things far worse. The prior locking changes @dtantsur mentioned makes some of that a lot better, but hopefully we're on a path to getting these issues resolved.

**Comment by dtantsur** [comment] 2023-08-24 16:34
Since staring at the code and the logs no longer helps much, I've created https://github.com/metal3-io/ironic-image/pull/430 that enables very extensive database debugging. Now we need to recheck the ubuntu job until it fails.

**Comment by lentzi90** [comment] 2023-08-25 10:22
This seems to be another occurrence: https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_release-1-4_e2e_feature_test_centos/143/
(Check the logs from remediation)

**Comment by dtantsur** [comment] 2023-08-25 11:24
Sigh, I need it to fail on my testing patch, but that simply does not happen.

**Comment by Sunnatillo** [comment] 2023-09-04 06:41
@dtantsur, your changes included in this test and I was able to reproduce it. Please check here:
https://jenkins.nordix.org/job/metal3_metal3_dev_env_release-1-5_integration_test_centos/19

**Comment by Sunnatillo** [comment] 2023-09-07 06:52
> @dtantsur, your changes included in[ this test PR](https://github.com/metal3-io/metal3-dev-env/pull/1290) and I was able to reproduce it. Please check here: https://jenkins.nordix.org/job/metal3_metal3_dev_env_release-1-5_integration_test_centos/19

One more test: 
https://jenkins.nordix.org/job/metal3_metal3_dev_env_release-1-5_integration_test_ubuntu/9

**Comment by dtantsur** [comment] 2023-09-11 11:37
I've just re-triggered the ironic-image build with the recent fixes. Please let me know how it goes from now on.

**Closed** 2023-09-13 06:56 UTC
Labels: kind/flake, triage/accepted
